### ISSUE TITLE
Installing has been nightmare :'(

### ISSUE THREAD

**Issue by krognome** [tembo-io/pg_vectorize#128]
I must be missing something bc installing all the dependencies and the pg_vectorize extension has been a nightmare. Do you guys simply use the Makefile in the extension directory to make and then make install? I am on Ubuntu and updated the Makefile with my DB credentials. It almost completes but errors out stating that the vectorize job does not exist. I am unable to find where the vectorize job is being made. After I installed each dependency one by one I noticed the Makefile may have the dependency install with it? I noticed that cron stated it can only be setup on the default postgres DB??? If so that kind of sucks huh? Most people who are going to use this already has a postgres DB and would not be using the docker image. To bad there is not a simple command to install this package and all of its dependencies.

**Comment by ChuckHend** [comment]
@krognome sorry you're having a bad experience. Easiest way to run the extension is on Tembo cloud, everything is set up for you there and you could migrate to it.

For installing someplace else, there are a ton of dependencies. `make setup` is the best bet. You could also give pgt.dev a try, but there are challenges depending on your OS and cpu architecture. To run it on a different database, you will need to set cron.database_name in your postgresql.conf.

**Comment by ChuckHend** [comment]
Also, here are some doc for changing the database that you want configured.
https://tembo.io/docs/product/stacks/ai/vectordb/configuration

**Comment by krognome** [comment]
NP I'll figure it out. I know the command line and server configuration pretty well so I will get it done. Just wanted to be sure there wasn't something I was missing or easier method than what I have been trying. I have a complete replica of live environment on my dev machine etc and have to be able to host anywhere. This extension will save me a ton of time in the end so I'm sure it's worth it.

**Comment by ChuckHend** [comment]
You can join our [community slack](https://join.slack.com/t/tembocommunity/shared_invite/zt-277pu7chi-NHtvHWvLhHwyK0Y5Y6vTPw) if you want some extra help. But let's leave this issue open 
We will make it easier to install.

**Comment by krognome** [comment]
Thank you. It's nice to see developers dedicated to their code and repository. I always feel fortunate when I come across a package that saves me and my team a lot of time and frustration in the end. I will post my solution once everything is setup and working well.

**Comment by krognome** [comment]
I ended up going with:  https://qdrant.tech/ it is open source and has everything we need for vector and RAG: https://github.com/qdrant/qdrant I am sure your product is awesome and perfect solution for many bc it works well with postgres so me going with this product says nothing against your product at all. Thank you for your assistance.

**Comment by ChuckHend** [comment]
> I ended up going with: https://qdrant.tech/ 

Sorry to see you go. If you find yourself looking again, or decide you want your data to live in a single data store, you could try the VectorDB Stack on [Tembo Cloud](https://cloud.tembo.io/) where everything you saw in this repo comes pre-installed.
