### ISSUE TITLE
documentation and examples for filtering

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pg_vectorize#143]
`vectorize.search()` supports some limited filtering (the filtering happens after vector similarity search) by using the [where](https://github.com/tembo-io/pg_vectorize/blob/9e013e3c9c5702c982ca74415ff396074a744cb7/extension/src/api.rs#L54) parameter, but we dont have any docs for this.

1. Add usage of this parameter to documentation including some examples, and
2. Provide some documentation on adding [partial indices ](https://github.com/pgvector/pgvector/issues/259)to a table (which will help improve filtering).

**Comment by asr2003** [comment]
Can I be assigned? @ChuckHend

**Comment by mobley-trent** [comment]
Hi @asr2003 I appreciate your interest in this issue but I attempted to tackle it first hence I think I should be assigned. We could split the bounty if you like
