### ISSUE TITLE
drop deprecated parameters from `vectorize.table()`

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pg_vectorize#146]
`search_alg` is deprecated, in favor of [index_dist_type](https://github.com/tembo-io/pg_vectorize/blob/9e013e3c9c5702c982ca74415ff396074a744cb7/extension/src/api.rs#L22). Drop search_alg from the parameter and downstream call tree.

**Comment by Bhavyajain21** [comment]
Can I be assigned? @ChuckHend
