### ISSUE TITLE
increase embedding provider support

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pg_vectorize#152]
add support for embeddings from:
- aws bedrock
- google vertex
- [azure ai](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/embeddings?tabs=console#how-to-get-embeddings)
- [voyage](https://docs.voyageai.com/docs/embeddings)

Embedding providers are added by implementing the required traits. For example see the implementation for [Cohere](https://github.com/tembo-io/pg_vectorize/blob/main/core/src/transformers/providers/cohere.rs)

**Comment by tavallaie** [comment]
not only embedding but also other things beside OLLAMA like calling api can help a lot, for example I can not use it with persian embedding and some other models.

**Comment by ChuckHend** [comment]
We do have support for Ollama (thanks to @destrex271) - but we are pretty light on documentation on using it is.

https://github.com/tembo-io/pg_vectorize/blob/main/core/src/transformers/providers/ollama.rs

**Comment by tavallaie** [comment]
can we change this 

> We do have support for Ollama (thanks to @destrex271) - but we are pretty light on documentation on using it is.
> 
> https://github.com/tembo-io/pg_vectorize/blob/main/core/src/transformers/providers/ollama.rs

can you change this to env variables and optional apikey ? so we can support other online ollama like compatible webservices

**Comment by ChuckHend** [comment]
Yes it can be changed. It is a configuration is Postgres:

When you run this with docker-compose it gets set to the docker service name by default.

```
postgres=# show vectorize.ollama_service_url ;
   vectorize.ollama_service_url   
----------------------------------
 http://ollama-serve:3001/v1/chat
(1 row)
```

but it can be set to whatever value you want, e.g. `ALTER SYSTEM SET vectorize.ollama_service_url to 'https://www.myservice.ai/embeddings'`.  The assumption here is that whatever service running at `vectorize.ollama_service_url` has an API (request and response) schema exactly like Ollama's.

Similarly, you can change the OpenAI url so long as the server running has the same API schema as OpenAI

```
postgres=# show vectorize.openai_service_url ;
 vectorize.openai_service_url 
------------------------------
 https://api.openai.com/v1
(1 row)
```

All the Postgres settings that can be changed are defined here: https://github.com/tembo-io/pg_vectorize/blob/main/extension/src/guc.rs

**Comment by tavallaie** [comment]
Let me try it

**Comment by ChuckHend** [comment]
Let me know if you run into any issues. Can ping me here, or in the Tembo community slack.

**Comment by tavallaie** [comment]
@palash25 please check #169 too. maybe your experience and attempt can help us with that issue too.

**Comment by palash25** [comment]
hi @ChuckHend  is the bounty per provider API or for all of 4 of the implementations? asking so that I can know if you expect smaller individual PRs for each API provider or one large PR containing all the implementations?

For now I have created a draft for the Voyage API just for visibility so that others know I am working on it and there is no duplication.

**Comment by ChuckHend** [comment]
The bounty will be for a single provider. We will need to open new bounties for each new provider though. I think going forward we'll have bounties for specific providers by name.

**Comment by ChuckHend** [comment]
and yes, as @tavallaie mentioned there is some discussion over in https://github.com/tembo-io/pg_vectorize/issues/169 where we hopefully can make it such that you can add new embedding providers by inserting rows to a table.

**Comment by ChuckHend** [comment]
any future work related to model provider support will fall under https://github.com/tembo-io/pg_vectorize/issues/169
