### ISSUE TITLE
Change default database

### ISSUE THREAD

**Issue by iakov-kaiumov** [tembo-io/pg_vectorize#168]
Is there any way to change default `postgres` database?

I was able to change default database for `pg_cron`. However, I don't know how to change default database in vectorize-pg extension (for example in this [line](https://github.com/tembo-io/pg_vectorize/blob/638b12887f14d47de0793b16d535b226d8f371b9/extension/src/util.rs#L22)).

**Comment by ChuckHend** [comment]
Yes, `ALTER SYSTEM SET vectorize.database_name TO 'my_new_db';`. Thanks for asking, I'll get this added to our docs.

That GUC is defined [here](https://github.com/tembo-io/pg_vectorize/blob/638b12887f14d47de0793b16d535b226d8f371b9/extension/src/guc.rs#L42).

**Comment by ChuckHend** [comment]
@iakov-kaiumov I've added this to the [documentation](https://tembo.io/pg_vectorize/configuration/#changing-the-database). Thank you again for asking!

If this works for you, please close the issue.

**Comment by iakov-kaiumov** [comment]
It works! Thanks!

BTW this project is awesome!
